# Generated by Django 2.0.6 on 2018-06-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('teacher_name', models.CharField(max_length=30)),
                ('capacity', models.IntegerField()),
                ('period', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Classtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.IntegerField()),
                ('course_identity', models.IntegerField()),
                ('course_name', models.CharField(max_length=30)),
                ('teacher_name', models.CharField(max_length=30)),
                ('course_capacity', models.IntegerField()),
                ('course_period', models.IntegerField()),
                ('course_time_1', models.IntegerField()),
                ('course_time_2', models.IntegerField(null=True)),
                ('classroom_identity_1', models.IntegerField()),
                ('classroom_identity_2', models.IntegerField(null=True)),
                ('classroom_name_1', models.CharField(max_length=30)),
                ('classroom_name_2', models.CharField(max_length=30, null=True)),
                ('classroom_capacity_1', models.IntegerField()),
                ('classroom_capacity_2', models.IntegerField(null=True)),
            ],
        ),
    ]
